name: Document Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        deno-version: [1.3.0]
        
    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
          
      - name: Lint Deno Module
        run: deno fmt --check
        
      - name: Build Deno Module
        run: deno run --reload document-creator.ts

      - name: Test Deno Module
        run: deno test --allow-none
        
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/document-service
        tag_with_sha: true
        tag_with_ref: true
